// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1:string,arg2:number,arg3:string,arg4:boolean,arg5:string,arg6:number,arg7:string):Promise<string>;
